### ISSUE TITLE
Multiple pages

### ISSUE THREAD

**Issue by byaka** [niklasb/webkit-server#20]
Is it possible to work with more then one page at time from python wrapper?

**Comment by niklasb** [comment]
No, you would have to have separate session instances for that.

**Comment by byaka** [comment]
Every session create new webkit instance?

**Comment by niklasb** [comment]
Only one instance of webkit-server will be started, but of course it will instantiate different QWebPages

**Comment by byaka** [comment]
Nice, it what i want!
