### ISSUE TITLE
is it qt5.6 supported ? or just qt4 

### ISSUE THREAD

**Issue by deter3** [niklasb/webkit-server#23]
I am trying to install webkit-server , I have installed qt5.6 on amazon ec2 linux ami server , but was always notified that "Project ERROR: Unknown module(s) in QT: webkitwidgets"  when run 
sudo python setup.py install 

I searched and just can not find "libqt5webkit5-dev " for CentOS or ec2 linux ami . 

I guess qt4 supported only , is it right ?

**Comment by niklasb** [comment]
Qt5 should work. That's what I'm using locally. However, maybe you need to
install qtwebkit as a separate package? I'm not familiar with CentOS
unfortunately.

**Comment by deter3** [comment]
I asked the same question on http://stackoverflow.com/questions/36099888/project-error-unknown-modules-in-qt-webkitwidgets-amazon-linux-ami-qt5-6-i   , turns out  webkit modules were removed from Qt 5.6 . 

see the release notes from http://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules .

**Comment by niklasb** [comment]
Yeah, Qt WebKit is definitely needed. From how I read the notes, you can still build it from source though.

**Comment by deter3** [comment]
sorry , I am commenting on the closed issues . Just want to provide more info. 

https://github.com/thoughtbot/capybara-webkit/issues/885  

capybara-webkit is only support qt5.5 . I suggest it's better to mention this in dryscrape readme to save others' time . I have spent around 3 days trying to figure out what's the problem .

**Comment by niklasb** [comment]
@deter3 I agree with you absolutely. I will put something in the docs about that.

**Comment by niklasb** [comment]
Done: https://github.com/niklasb/dryscrape/commit/02e9a04d06c691f59bdeb18f611950cd1cccff22 https://github.com/niklasb/webkit-server/commit/3393fa92cde57b5a8b4aaf3920c070e53f706146
