### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webkitwidgets

### ISSUE THREAD

**Issue by kushagraSahu** [niklasb/webkit-server#24]
(In Ubuntu14.04)After cloning the repo running- python setup.py install, I get:

```
Project ERROR: Unknown module(s) in QT: webkitwidgets
make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3
error: [Errno 2] No such file or directory: 'src/webkit_server'

----------------------------------------
```

Command "/home/kushagra/{{appname}}/venv/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-1667tw7m-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-_eix3qn3-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kushagra/{{appname}}/venv/include/site/python3.4/webkit-server" failed with error code 1 in /tmp/pip-1667tw7m-build/

Please help. @niklasb  @jferris

**Comment by kushagraSahu** [comment]
Also, 
qmake -v
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Qt-5.5.1/lib

**Comment by samjiks** [comment]
Try installing qt instead of qt5

**Comment by samjiks** [comment]
The 5.6 version of Qt removes the Qt WebKit module in favor of the new module Qt WebEngine. So far webkit-server has not been ported to WebEngine (and likely won't be in the near future), so Qt <= 5.5 is a requirement.

**Comment by kushagraSahu** [comment]
Thanks @samjiks.
